services:
  - type: web
    name: portfolio
    runtime: python
    buildCommand: chmod +x build_files.sh && ./build_files.sh
    startCommand: gunicorn portfolio.wsgi:application
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: PYTHON_VERSION
        value: 3.10.13
    plan: free 