services:
  - type: web
    name: portfolio
    runtime: python
    buildCommand: chmod +x build_files.sh && ./build_files.sh
    startCommand: chmod +x start.sh && ./start.sh
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: PYTHON_VERSION
        value: 3.10.13
      - key: PORT
        value: 8000
      - key: WEB_CONCURRENCY
        value: 1
    plan: free
    healthCheckPath: /health/ 